// actions types

export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_HEADER_DATA = 'LOAD_HEADER_DATA'
export const LOAD_OPT_DATA = 'LOAD_OPT_DATA'
export const LOAD_CVV_CARD_DATA = 'LOAD_CVV_CARD_DATA'
export const LOAD_UNLOCK_QUESTIONES_DATA = 'LOAD_UNLOCK_QUESTIONES_DATA'
export const LOAD_DASHBOARD_HEADER_DATA = 'LOAD_DASHBOARD_HEADER_DATA'
export const LOAD_CONTACT_RM_DATA = 'LOAD_CONTACT_RM_DATA'
export const LOAD_TRANSACTION_HISTORY_DATA = 'LOAD_TRANSACTION_HISTORY_DATA'
export const LOAD_MANAGE_CARD_DATA = 'LOAD_MANAGE_CARD_DATA'
export const LOAD_MANAGE_PROFILE_DATA = 'LOAD_MANAGE_PROFILE_DATA'
export const LOAD_MANAGE_ACCESS_ACCESS_DASHBOARD_DATA = 'LOAD_MANAGE_ACCESS_ACCESS_DASHBOARD_DATA'
export const LOAD_MANAGE_ACCESS_USER_LISTS_DATA = 'LOAD_MANAGE_ACCESS_USER_LISTS_DATA'
export const LOAD_ALERT_FAQS_DATA = 'LOAD_ALERT_FAQS_DATA'
export const LOAD_ESTATEMENTS_DATA = 'LOAD_ESTATEMENTS_DATA'
export const LOAD_FINANCE_MANAGER_DATA = 'LOAD_FINANCE_MANAGER_DATA'
export const LOAD_MOVE_PAYMENT_DATA = 'LOAD_MOVE_PAYMENT_DATA'
// Move Payment data
export const LOAD_MOVE_PAYMENT_TRANSFER_BETWEEN_ACCOUNTS_DATA =
  'LOAD_MOVE_PAYMENT_TRANSFER_BETWEEN_ACCOUNTS_DATA'
export const LOAD_MOVE_PAYMENT_ONLINE_TRANSACTION_STATUS_DATA =
  'LOAD_MOVE_PAYMENT_ONLINE_TRANSACTION_STATUS_DATA'
export const LOAD_MOVE_PAYMENT_MANAGE_DIRECT_DEBITS_DATA =
  'LOAD_MOVE_PAYMENT_MANAGE_DIRECT_DEBITS_DATA'
export const LOAD_MOVE_PAYMENT_APPROVE_TRANSACTIONS_DATA =
  'LOAD_MOVE_PAYMENT_APPROVE_TRANSACTIONS_DATA'
export const LOAD_MOVE_PAYMENT_MANAGE_STANDING_ORDERS_DATA =
  'LOAD_MOVE_PAYMENT_MANAGE_STANDING_ORDERS_DATA'
export const LOAD_MOVE_PAYMENT_MANAGE_PAYMENT_TEMPLATE_DATA =
  'LOAD_MOVE_PAYMENT_MANAGE_PAYMENT_TEMPLATE_DATA'
export const LOAD_MOVE_PAYMENT_MANAGE_PAYEES_DATA = 'LOAD_MOVE_PAYMENT_MANAGE_PAYEES_DATA'
export const SAVE_TRANSFER_BETWEEN_ACCOUNTS = 'SAVE_TRANSFER_BETWEEN_ACCOUNTS_DATA'
export const LOAD_HELP_SUPPORT_DATA = 'LOAD_HELP_SUPPORT_DATA'
export const LOAD_MARKETINGPREFERENCES_DATA = 'LOAD_MARKETINGPREFERENCES_DATA'
