export const REGISTER_RSP_LOCAL_KEY = 'REGISTER:COMPLETED_RSP'
export const REGISTER_OTP_RSP_LOCAL_KEY = 'REGISTER:OTP_COMPLETED_RSP'
export const REGISTER_CONFIRM_RSP_LOCAL_KEY = 'REGISTER:CONFIRM_COMPLETED_RSP'
